language: java
before_install:
  - sudo apt-get update -qq
  - sudo apt-get upgrade -y
  - sudo apt-get dist-upgrade -y
  - sudo apt-get -y install ia32-libs-multiarch
script: mvn test -Djava.net.preferIPv4Stack=true
