language: java
before_install:
  - sudo dpkg --add-architecture i386
  - sudo sed -i -e's/[arch=amd64]/[arch=amd64,i386]/' /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get -y upgrade
  - sudo apt-get -y dist-upgrade
script: mvn test -Djava.net.preferIPv4Stack=true
